spring:
  datasource:
    url: jdbc:postgresql://ibwedu.f3322.net:5422/test
    username: test
    password: 123456
  redis:
    host: 127.0.0.1
    database: 4
    port: 6379
    timeout: 10000
    jedis:
      pool:
        max-active:  8 #最大连接数
        max-wait: -1   #最大阻塞等待时间(负数表示没限制)
        max-idle: 8  #最大空闲
        min-idle: 0  #最小空闲
  servlet:
       multipart:
         enabled: true
         max-file-size: 500MB
         max-request-size: 500MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8111

sim:
  # jwt 配置
  jwt:
    # jwt token 有效时间 单位是秒
    expired-in: '25920000' # 登录有效时间 7 * 24 小时
    # 使用非对称加密算法 rs256, 自动生成私钥，公钥可以从服务器获取
    algorithm: 'rs256'
    private-key: ''

kvm:
  docker:
    start-port: 40000
    count: 500
    server-info:
      - 'node1@tcp://192.168.2.41:2375'
    cert-path:
      - "/home/certs"

ftp:
  ftpIp: ibwedu.f3322.net
  ftpUser: test
  ftpPass: 123456



